MODEL:
  META_ARCHITECTURE: "FsodRCNN"
  BACKBONE: 
    NAME: "FsodPyramidVisionTransformerV2"
    FREEZE_AT: 3
  PROPOSAL_GENERATOR:
    NAME: "AttentionRPN" #"CrossScalesRPN"  
  RPN:
    PRE_NMS_TOPK_TEST: 6000
    POST_NMS_TOPK_TEST: 100
  ROI_HEADS:
    NAME: "FsodStandardROIHeads"
    BATCH_SIZE_PER_IMAGE: 128
    POSITIVE_FRACTION: 0.5
    NUM_CLASSES: 1
    SCORE_THRESH_TEST: 0.0
  ROI_BOX_HEAD:
    NAME: "FsodPVT4BoxHead"
DATASETS:
  TRAIN: ("coco_2017_train_nonvoc",)
  TEST: ("coco_2017_val",)
DATALOADER:
  NUM_WORKERS: 8
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.0002
  STEPS: (7500, 10000)
  MAX_ITER: 120000
  WARMUP_ITERS: 500
  WARMUP_FACTOR: 0.1
  CHECKPOINT_PERIOD: 5000
  HEAD_LR_FACTOR: 2.0
INPUT:
  FS:
    ENABLED: True
    SUPPORT_WAY: 2
    SUPPORT_SHOT: 30
  MIN_SIZE_TRAIN: (440, 472, 504, 536, 568, 600)
  MAX_SIZE_TRAIN: 1000
  MIN_SIZE_TEST: 600
  MAX_SIZE_TEST: 1000
VERSION: 2
