__BASE__: "training-pvtv2-retinanet.yaml"
MODEL:
  BACKBONE:
    FREEZE_AT: 5
    ## ACCIDENTALLY REMOVED IN PVT?
    TRAIN_BRANCH_EMBED: False
SOLVER:
  STEPS: (3000, 5000)
  MAX_ITER: 5000
  WARMUP_ITERS: 200
  CHECKPOINT_PERIOD: 5000
ROI_HEADS:
    ONLY_TRAIN_NORM: True
INPUT:
  FS:
    FEW_SHOT: True