_BASE_: "pascalvoc.yaml"
DATASETS:
  TRAIN: ("voc_2007_trainval_base1", "voc_2012_trainval_base1") # Finetuning: ("voc_2007_trainval_all1_kshot",)
  TEST: ("voc_2007_test_all1",)
  TEST_KEEPCLASSES: 'all1'