__BASE__: "pretraining-pvtv2-retinanet.yaml"
MODEL:
  META_ARCHITECTURE: "FsodRCNN"
  BACKBONE: 
    NAME: "build_retinanet_fsod_pvtv2_fpn_backbone"
  PROPOSAL_GENERATOR:
    NAME: "FsodRPN"  
  RPN:
    PRE_NMS_TOPK_TEST: 12000
    POST_NMS_TOPK_TEST: 100
  ROI_HEADS:
    NAME: "FsodStandardROIHeads"
    BATCH_SIZE_PER_IMAGE: 128
    NUM_CLASSES: 1
    SCORE_THRESH_TEST: 0.0
  ROI_BOX_HEAD:
    NAME: "FsodPVT4BoxHead"
  BACKBONE:
    FREEZE_AT: 3
DATALOADER:
  NUM_WORKERS: 8
DATASETS:
  TEST_SHOTS: (10,) #(1,2,3,5,10,30)
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.0002
  STEPS: (7500, 10000)
  MAX_ITER: 20000
  WARMUP_ITERS: 500
  WARMUP_FACTOR: 0.1
  CHECKPOINT_PERIOD: 10000
  HEAD_LR_FACTOR: 2.0
INPUT:
  FS:
    ENABLED: True
    SUPPORT_WAY: 2
    SUPPORT_SHOT: 30
VERSION: 2
