_BASE_: "Base-FSOD-C4.yaml"
MODEL:
  PIXEL_MEAN: [103.530, 116.280, 123.675]
  PIXEL_STD: [57.375, 57.120, 58.395]
  WEIGHTS: "./output/fsod/single_branch_pretraining_dota_pvt_v2_b2_li/model_final.pth"
  MASK_ON: False
OUTPUT_DIR: './output/fsod/two_branch_training_dota_pvt_v2_b2_li'
DATA_DIR: './datasets/data/dota_dataset'
DATASETS:
  TRAIN: ("dota_2014_train_nonvoc",)
  TEST: ("dota_2014_val2",) #("dota_2014_val",)
  TEST_SHOTS: (10,) #(1,2,3,5,10,30)
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 600
  MAX_SIZE_TEST: 1000
